# Site settings
title: Nice Blog
name: Nice Blog # your name
email: youremail@example.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "/Nice_Blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username: # your Github username
disqus_username: # your disqus username

google-analytics: # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown

theme: jekyll-theme-architect
<!-- Gitalk 评论 start  -->

<!-- Link Gitalk 的支持文件  -->
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://unpkg.com/gitalk@latest/dist/gitalk.min.js"></script> 
<div id="gitalk-container"></div>     <script type="text/javascript">
    var gitalk = new Gitalk({

  # 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 3af8a7794d812af51134                           #生成的clientID
  clientSecret: 8af62c8fd55ef7c229bbcce3e10acd9169d314c1    #生成的clientSecret
  repo: future1.github.io    #仓库名称
  owner:futureoracle    #github用户名
  admin: futureoracle 
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
